ASP.net-MVC-5-Automated-Teller-Machine-master/ASP.net-MVC-5-Automated-Teller-Machine-master/AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;

namespace AutomatedTellerMachine.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details/5
        public ActionResult Details()
        {
			var checkingAccount = new CheckingAccount {AccountNumber = "00001234", Balance = 200.23m, FirstName = "Sebastian", LastName = "Jaronczyk", Id = 0};
            return View(checkingAccount);
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP.net-MVC-5-Automated-Teller-Machine-master/ASP.net-MVC-5-Automated-Teller-Machine-master/AutomatedTellerMachine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;

namespace AutomatedTellerMachine.Controllers
{
	public class HomeController : Controller
	{
		private ApplicationDbContext db = new ApplicationDbContext();

		[Authorize]
		public ActionResult Index()
		{
			var userId = User.Identity.GetUserId();
			var checkinAccountId = db.CheckingAccounts.First(c => c.ApplicationUserId == userId).Id;
			ViewBag.CheckingAccountId = checkinAccountId;
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

		public ActionResult Serial(string letterCase)
		{
			var serial = "ASPNETMVC5ATM1";
			if (letterCase == "lower")
			{
				return Content(serial.ToLower());
			}
			return Content(serial);
			//return new HttpStatusCodeResult(403);
			//return Json(new {name = "serial", value = serial}, JsonRequestBehavior.AllowGet);
			//return RedirectToAction("Index");
		}
	}
}

ASP.net-MVC-5-Automated-Teller-Machine-master/ASP.net-MVC-5-Automated-Teller-Machine-master/AutomatedTellerMachine/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;

namespace AutomatedTellerMachine.Controllers
{
	[Authorize]
    public class TransactionController : Controller
    {
		private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transaction/deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

		[HttpPost]
		public ActionResult Deposit(Transaction transaction)
		{
			if (ModelState.IsValid)
			{
				db.Transactions.Add(transaction);
				db.SaveChanges();
				return RedirectToAction("Index", "Home");
			}
			return View();
		}
	}
}

ASP.net-MVC-5-Automated-Teller-Machine-master/ASP.net-MVC-5-Automated-Teller-Machine-master/AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ASP.net-MVC-5-Automated-Teller-Machine-master/ASP.net-MVC-5-Automated-Teller-Machine-master/AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASP.net-MVC-5-Automated-Teller-Machine-master/ASP.net-MVC-5-Automated-Teller-Machine-master/AutomatedTellerMachine/Views/Home/Index.cshtml
@using AutomatedTellerMachine.Models
@{
	ViewBag.Title = "Home Page";
}


<div class="row">
	<div class="col-md-6 margin-top-20">
		<a href="#" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-down"></span> Withdrawal</a>
		<a href="#" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-flash"></span> Quick Cash $100</a>
		<a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry</a>
	</div>
	<div class="col-md-6 margin-top-20">
		<a href="#" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-print"></span> Print Statement</a>
		<a href="#" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
		<a href="@Url.Action("Deposit", "Transaction", new {CheckingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span> Deposit</a>
	</div>
</div>